### ISSUE TITLE
/VMovie/models 找不到，  go get也下载不了

### ISSUE THREAD

**Issue by epiphyllum** [zituocn/22v#1]
 ~/workspace/beego-samples/src/github.com/zituocn/22v/ [master] bee run

---

| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  **/
__**/  _**| _**| v1.5.0
2016/08/30 10:48:16 [INFO] Using '22v' as 'appname'
2016/08/30 10:48:16 [INFO] Detected bee.json
2016/08/30 10:48:16 [INFO] Initializing watcher...
2016/08/30 10:48:16 [TRAC] Directory(/Users/hary/workspace/beego-samples/src/github.com/zituocn/22v/controllers/admin)
2016/08/30 10:48:16 [TRAC] Directory(/Users/hary/workspace/beego-samples/src/github.com/zituocn/22v/controllers)
2016/08/30 10:48:16 [TRAC] Directory(/Users/hary/workspace/beego-samples/src/github.com/zituocn/22v)
2016/08/30 10:48:16 [TRAC] Directory(/Users/hary/workspace/beego-samples/src/github.com/zituocn/22v/models)
2016/08/30 10:48:16 [TRAC] Directory(/Users/hary/workspace/beego-samples/src/github.com/zituocn/22v/routers)
2016/08/30 10:48:16 [INFO] Start building...
controllers/api.go:7:2: cannot find package "github.com/zituocn/VMovie/models" in any of:
    /usr/local/Cellar/go/1.6.2/libexec/src/github.com/zituocn/VMovie/models (from $GOROOT)
    /Users/hary/workspace/beego-samples/src/github.com/zituocn/VMovie/models (from $GOPATH)
2016/08/30 10:48:16 [ERRO] ============== Build failed ===================

**Comment by zituocn** [comment]
请更改22v目录名为VMovie
