### ISSUE TITLE
go get 下载不了

### ISSUE THREAD

**Issue by youmisun** [zituocn/22v#3]
go get -v github.com/zituocn/22v
打印如下信息
github.com/zituocn/VMovie (download)
# cd .; git clone https://github.com/zituocn/VMovie E:\go\src\github.com\zituocn\VMovie
Cloning into 'E:\go\src\github.com\zituocn\VMovie'...
remote: Repository not found.
fatal: repository 'https://github.com/zituocn/VMovie/' not found
package github.com/zituocn/VMovie/models: exit status 128
package github.com/zituocn/VMovie/routers: cannot find package "github.com/zituocn/VMovie/routers" in any of:
        C:\Go\src\github.com\zituocn\VMovie\routers (from $GOROOT)
        E:\go\src\github.com\zituocn\VMovie\routers (from $GOPATH)
package github.com/zituocn/VMovie/task: cannot find package "github.com/zituocn/VMovie/task" in any of:
        C:\Go\src\github.com\zituocn\VMovie\task (from $GOROOT)
        E:\go\src\github.com\zituocn\VMovie\task (from $GOPATH)

**Comment by zituocn** [comment]
git clone https://github.com/zituocn/22v.git

然后把 22v目录改成VMovie，再go build。
如果缺少什么第三方包，请自行获取。
